# Support Vector Machines (SVMs) using scikit-learn in Python
Hi Guys,<br>

Welcome to the Support Vector Machines lecture using scikit-learn in Python.<br>

As suggested in the theory lecture, we are going to work with a real dataset on [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/uciml/breast-cancer-wisconsin-data/data). <br><br>

<font style="font-size:12px;color:green;">&#9758; The dataset is available on kaggle and originally belong to [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29). This dataset was donated to UCI by Nick Street in 1995 for the public use. [Relevant Papers](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29) and [detailed description](https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.names) on the dataset is provided at UCI website.<br></font>

Because we have worked with this dataset in Logistic Regression and KNN sections, so, this will allow us to compare the SVM to those models. However, in the SVM project, we will work with another new and real life dataset on credit approval. <br>

&#9758; Breast cancer dataset can be loaded from Scikit-learn. Its up to you if you want to load from scikit-learn or use csv data file which is provided in the course material.<br>
I am going to load the one which is in the course material!<br>
First thing first, let's import some libraries!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('Breast_Cancer_Diagnostic.csv')

In [3]:
df

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean diagnosis  
0                   0.07871         M  
1                   0.05667         M  
2                   0.05999         M  
3                   0.09744         M  
4                   0.05883         M  
..                      ...       ...  
564                 0.05623         M  
565                 0.05533         M  
566                 0.05648         M  
567                 0.07016         M  
568                 0.05884         B  

[569 rows x 11 columns]

In [4]:
df.isnull().sum()

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           0
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             0
fractal_dimension_mean    0
diagnosis                 0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   radius_mean             569 non-null    float64
 1   texture_mean            569 non-null    float64
 2   perimeter_mean          569 non-null    float64
 3   area_mean               569 non-null    float64
 4   smoothness_mean         569 non-null    float64
 5   compactness_mean        569 non-null    float64
 6   concavity_mean          569 non-null    float64
 7   concave points_mean     569 non-null    float64
 8   symmetry_mean           569 non-null    float64
 9   fractal_dimension_mean  569 non-null    float64
 10  diagnosis               569 non-null    object 
dtypes: float64(10), object(1)
memory usage: 49.0+ KB


In [6]:
x = df.drop('diagnosis',axis = 1)
y = df['diagnosis']

In [7]:
x

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  
0                   0.07871  
1                   0.05667  
2                   0.05999  
3                   0.09744  
4                   0.05883  
..                      ...  
564                 0.05623  
565                 0.05533  
566                 0.05648  
567                 0.07016  
568                 0.05884  

[569 rows x 10 columns]

In [8]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
#now scaling for features
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
x_scaler = mms.fit_transform(x)
x_scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.73111332, 0.68636364,
        0.60551811],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.34875746, 0.37979798,
        0.14132266],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.63568588, 0.50959596,
        0.21124684],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.26351889, 0.26767677,
        0.13732098],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.7554672 , 0.67525253,
        0.42544229],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.26616162,
        0.18702612]], shape=(569, 10))

In [10]:
x_scaler.shape

(569, 10)

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x_scaler,y,test_size = 0.20,random_state = 42)

In [13]:
x_train

array([[0.09692839, 0.25769361, 0.10365559, ..., 0.21744533, 0.53080808,
        0.64237574],
       [0.66775522, 0.57017247, 0.68350494, ..., 0.74353877, 0.67424242,
        0.50589722],
       [0.10374367, 0.14034494, 0.10648884, ..., 0.1083499 , 0.6469697 ,
        0.4142797 ],
       ...,
       [0.34592267, 0.2404464 , 0.32140142, ..., 0.03106362, 0.22626263,
        0.0800337 ],
       [0.33125089, 0.33513696, 0.32706793, ..., 0.32122266, 0.30757576,
        0.32603201],
       [0.24605992, 0.36557322, 0.23101375, ..., 0.08797217, 0.34292929,
        0.14342881]], shape=(455, 10))

In [14]:
x_train.shape

(455, 10)

In [15]:
x_test

array([[0.25978513, 0.30064254, 0.25775689, ..., 0.18991054, 0.43686869,
        0.29001685],
       [0.56599934, 0.39228948, 0.55151683, ..., 0.39517893, 0.26363636,
        0.09793597],
       [0.4012968 , 0.33040243, 0.40017967, ..., 0.40193837, 0.43989899,
        0.168492  ],
       ...,
       [0.21482323, 0.17653027, 0.207864  , ..., 0.14557654, 0.41565657,
        0.24684078],
       [0.34260968, 0.61345959, 0.33694976, ..., 0.21908549, 0.14242424,
        0.23862679],
       [0.65071702, 0.72404464, 0.63513233, ..., 0.42972167, 0.35808081,
        0.14279697]], shape=(114, 10))

In [16]:
x_test.shape

(114, 10)

In [17]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [18]:
y_test.shape

(114,)

In [19]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [20]:
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(x_train,y_train)

SVC()

In [21]:
svm_model.score(x_test,y_test)

0.9736842105263158

In [22]:
svm_model = SVC(kernel = 'linear', C = 30, gamma = 'auto')
svm_model.fit(x_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [23]:
svm_model.score(x_test,y_test)

0.9298245614035088

# Now Using GridSerachCV(hyperperametar Tuning)

In [24]:
cancer_data = pd.read_csv('Breast_Cancer_Diagnostic.csv')
cancer_data

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean diagnosis  
0                   0.07871         M  
1                   0.05667         M  
2                   0.05999         M  
3                   0.09744         M  
4                   0.05883         M  
..                      ...       ...  
564                 0.05623         M  
565                 0.05533         M  
566                 0.05648         M  
567                 0.07016         M  
568                 0.05884         B  

[569 rows x 11 columns]

In [25]:
x = cancer_data.drop(['diagnosis'],axis=1)
x

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  
0                   0.07871  
1                   0.05667  
2                   0.05999  
3                   0.09744  
4                   0.05883  
..                      ...  
564                 0.05623  
565                 0.05533  
566                 0.05648  
567                 0.07016  
568                 0.05884  

[569 rows x 10 columns]

In [26]:
y=cancer_data['diagnosis']
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [27]:
type(y)

pandas.core.series.Series

### Now scaling features 

In [28]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
x_scaler = mms.fit_transform(x)
x_scaler

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.73111332, 0.68636364,
        0.60551811],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.34875746, 0.37979798,
        0.14132266],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.63568588, 0.50959596,
        0.21124684],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.26351889, 0.26767677,
        0.13732098],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.7554672 , 0.67525253,
        0.42544229],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.26616162,
        0.18702612]], shape=(569, 10))

### using GridSearchCV

In [29]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

clf = GridSearchCV((SVC()),{
    'gamma':['auto','scale'],
    'C':[1,5,10,15],
    'kernel':['rbf','linear','poly']
},cv=5)
clf.fit(x_scaler,y)
clf.cv_results_

{'mean_fit_time': array([0.00785494, 0.00528779, 0.00924821, 0.00589247, 0.00382228,
        0.00595975, 0.00458908, 0.0043623 , 0.00683112, 0.00587492,
        0.00409431, 0.00868402, 0.00479169, 0.00374417, 0.00439024,
        0.0046319 , 0.00356855, 0.0124177 , 0.00500302, 0.00504541,
        0.0043447 , 0.00631371, 0.00598292, 0.01396937]),
 'std_fit_time': array([9.04871865e-04, 1.27085693e-03, 1.78671413e-03, 5.84950767e-04,
        1.50843906e-04, 5.15643003e-04, 5.98076130e-04, 3.75809985e-04,
        6.26908013e-04, 2.28589955e-04, 1.53917200e-04, 9.03934739e-04,
        1.63738645e-04, 2.72719358e-04, 9.75560348e-05, 1.72514952e-04,
        3.59143435e-04, 3.21346655e-03, 2.44567282e-04, 8.03560144e-04,
        1.90050148e-04, 4.42130489e-04, 2.12778773e-03, 1.69722120e-03]),
 'mean_score_time': array([0.00565643, 0.00264153, 0.00333099, 0.00386605, 0.00186014,
        0.00170541, 0.00321636, 0.00221477, 0.00281205, 0.00327415,
        0.00209332, 0.0016335 , 0.00348058, 0.00

In [30]:
data = pd.DataFrame(clf.cv_results_)
data

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.007855      0.000905         0.005656        0.000900        1   
1        0.005288      0.001271         0.002642        0.000482        1   
2        0.009248      0.001787         0.003331        0.000467        1   
3        0.005892      0.000585         0.003866        0.000748        1   
4        0.003822      0.000151         0.001860        0.000052        1   
5        0.005960      0.000516         0.001705        0.000073        1   
6        0.004589      0.000598         0.003216        0.000477        5   
7        0.004362      0.000376         0.002215        0.000128        5   
8        0.006831      0.000627         0.002812        0.000329        5   
9        0.005875      0.000229         0.003274        0.000096        5   
10       0.004094      0.000154         0.002093        0.000074        5   
11       0.008684      0.000904         0.001634        0.000163        5   
12       0.004792      0.000164         0.003481        0.000491       10   
13       0.003744      0.000273         0.001545        0.000075       10   
14       0.004390      0.000098         0.001914        0.000147       10   
15       0.004632      0.000173         0.002415        0.000031       10   
16       0.003569      0.000359         0.001582        0.000039       10   
17       0.012418      0.003213         0.002016        0.000177       10   
18       0.005003      0.000245         0.003519        0.000427       15   
19       0.005045      0.000804         0.002198        0.000383       15   
20       0.004345      0.000190         0.001916        0.000174       15   
21       0.006314      0.000442         0.003044        0.000141       15   
22       0.005983      0.002128         0.002250        0.000660       15   
23       0.013969      0.001697         0.001919        0.000257       15   

   param_gamma param_kernel                                           params  \
0         auto          rbf       {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
1         auto       linear    {'C': 1, 'gamma': 'auto', 'kernel': 'linear'}   
2         auto         poly      {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
3        scale          rbf      {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}   
4        scale       linear   {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}   
5        scale         poly     {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}   
6         auto          rbf       {'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}   
7         auto       linear    {'C': 5, 'gamma': 'auto', 'kernel': 'linear'}   
8         auto         poly      {'C': 5, 'gamma': 'auto', 'kernel': 'poly'}   
9        scale          rbf      {'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}   
10       scale       linear   {'C': 5, 'gamma': 'scale', 'kernel': 'linear'}   
11       scale         poly     {'C': 5, 'gamma': 'scale', 'kernel': 'poly'}   
12        auto          rbf      {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
13        auto       linear   {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}   
14        auto         poly     {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}   
15       scale          rbf     {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
16       scale       linear  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}   
17       scale         poly    {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}   
18        auto          rbf      {'C': 15, 'gamma': 'auto', 'kernel': 'rbf'}   
19        auto       linear   {'C': 15, 'gamma': 'auto', 'kernel': 'linear'}   
20        auto         poly     {'C': 15, 'gamma': 'auto', 'kernel': 'poly'}   
21       scale          rbf     {'C': 15, 'gamma': 'scale', 'kernel': 'rbf'}   
22       scale       linear  {'C': 15, 'gamma': 'scale', 'kernel': 'linear'}   
23       scale         poly    {'C': 15, 'gamma': 'scale', 'kernel': 'poly'}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0

In [31]:
best_results = clf.best_score_
best_results

np.float64(0.956047197640118)

In [32]:
best_params = clf.best_params_
best_params

{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}

## Cross Validation

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
sv1 = cross_val_score(SVC(kernel='poly',C=10,gamma = 'scale'),x_scaler,y,cv=5)
sv1

array([0.93859649, 0.96491228, 0.94736842, 0.95614035, 0.96460177])

In [35]:
sv1.mean()

np.float64(0.9543238627542306)

In [37]:
sv2 = cross_val_score(SVC(kernel='rbf',C=1,gamma = 'auto'),x_scaler,y,cv=5)
sv2

array([0.85964912, 0.92105263, 0.92982456, 0.93859649, 0.95575221])

In [38]:
sv2.mean()

np.float64(0.9209750038813848)